apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberbs
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberbs
  template:
      metadata:
        labels:
          app: kuberbs
      spec:
        priorityClassName: system-cluster-critical
        serviceAccountName: default
        containers:
        - name: "kuberbs"
          # TODO image: doitintl/kuberbs:latest
          image: gcr.io/aviv-playground/kuberbs:latest
          # TDOD only for dev
          imagePullPolicy: Always
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
        restartPolicy: Always
        volumes:
          - name: google-cloud-key
            secret:
              secretName: kuberbs-key


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kuberbs-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
