apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuberbs.doit-intl.com
spec:
  group: doit-intl.com
  version: v1
  scope: Cluster
  names:
    plural: kuberbs
    singular: kuberb
    kind: Rbs
    shortNames:
    - rbs