apiVersion: "doit-intl.com/v1"
kind: Rbs
metadata:
    name: my-rbs-example
spec:
  watchperiod: 5
  metricssource: stackdriver
  namespaces:
  - name: default
    deployments:
    - deployment:
        name: hello-kubernetes-app
        #Stack driver metric
        metric: logging.googleapis.com/user/hello-kubernetes-app-errors
        threshold: 1
    - deployment:
        name: kubernetes-app-2
        # DataDog metric
        metric: gcp.container.cpu.usage_time{*}
        threshold: 85
  - name: kube-system
    deployments:
    - deployment:
        name: kube-dns
        metric: logging.googleapis.com/user/dig
