# Default values for kuberbs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: doitintl/kuberbs
  tag: latest
  pullPolicy: IfNotPresent

google_application_credentials: /var/secrets/google/key.json  

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

configmap:
    kuberbs_checkmetricsinterval: 10

nodeSelector: {}

tolerations: []

affinity: {}
